### ISSUE TITLE
วาดฉาก Background

### ISSUE THREAD

**Issue by KarnPrasai** [KarnPrasai/ScratchProjectGroup11#14]
วาด Backเround
-จุดเริ่มเกม (ห้องพัก)
-Map หลัก (ในหมาวิทยาลัย)
-ห้องส่งงาน

**Comment by Donutcmu** [comment]
![20230905_022342666_iOS](https://github.com/KarnPrasai/ScratchProjectGroup11/assets/141747348/a0279c5c-368a-48c9-b30e-45e650d470a6)
![20230905_022511748_iOS](https://github.com/KarnPrasai/ScratchProjectGroup11/assets/141747348/34455ce4-43d7-4185-a1d3-9d91d643087e)
![20230905_023649206_iOS](https://github.com/KarnPrasai/ScratchProjectGroup11/assets/141747348/fea91a42-9176-470e-abf7-f32bc6de7067)
![20230905_025233977_iOS](https://github.com/KarnPrasai/ScratchProjectGroup11/assets/141747348/6068b862-9201-499d-b45a-ce872333d31e)
![20230905_031017913_iOS](https://github.com/KarnPrasai/ScratchProjectGroup11/assets/141747348/8592135b-40eb-4c86-9de7-6e4e427376ba)

**Comment by Donutcmu** [comment]
![20230905_032513817_iOS](https://github.com/KarnPrasai/ScratchProjectGroup11/assets/141747348/f0203c33-5918-4166-b4c4-9946c912f54b)
