### ISSUE TITLE
วาด ตัวละคร & Game Object

### ISSUE THREAD

**Issue by KarnPrasai** [KarnPrasai/ScratchProjectGroup11#15]
-ตัวละครหลัก
-Mobs
-Items
-Traps

**Comment by Donutcmu** [comment]
![20230905_090753066_iOS](https://github.com/KarnPrasai/ScratchProjectGroup11/assets/141747348/07c4b1e3-c89a-453e-ab75-e65f5bdcdf01)
![20230906_092452539_iOS](https://github.com/KarnPrasai/ScratchProjectGroup11/assets/141747348/7ccb8438-c121-4ded-b861-48e8c53696f7)
![20230831_065623654_iOS](https://github.com/KarnPrasai/ScratchProjectGroup11/assets/141747348/27398353-6832-4bd6-9b07-8f5db081615c)
![Uploa
![20230905_162506513_iOS](https://github.com/KarnPrasai/ScratchProjectGroup11/assets/141747348/a7bd5878-c352-4625-8686-b072dfcf5012)
ding 20230905_160421432_iOS.png…]()
