### ISSUE TITLE
Final Test

### ISSUE THREAD

**Issue by KarnPrasai** [KarnPrasai/ScratchProjectGroup11#20]
ทดสอบเกมครั้งสุดท้าย

**Comment by DAVIESBACK** [comment]
เจอบัค รถมาแค่เสียงตัวรถไม่มา
คิดว่าน่าจะเป็นที่เครื่องสลับหน้าจนเว็บบัค

**Comment by DAVIESBACK** [comment]
บางทีขวดเหล้าที่ปาพร้อมกันโดนดาเมจแค่อันเดียว
มันอาจจะแค่คิดดาเมจรวม
เจอต้นเหตุแล้วทิชชู่มเกิดใต้เท้าพอดี
ลองรับดาเมจดูแล้วโดนตามปกติ

**Comment by Donutcmu** [comment]
Good

**Comment by DAVIESBACK** [comment]
เล่นจบแล้วได้Aกดretry/main menuได้ปกติ เสียงเอฟเฟกต์มันมาก
*ทิชชู่ที่เหลือในฉากรถหายไม่ทันเปลี่ยนฉาก เหมือนมันจะเป็นบัคเล็กๆตรงนี้
อยากให้เปลี่ยนฉากแล้วของดรอปหายไปเลย
ตัวหมาและเพื่อนเสียงเวลาโดนตีมีเสียงปกติ 
เวลาตัวเราโดนตีเลือดลดปกติมีเสียงปกติ 
เวลารถชนมีเสียงปกติ
เสียงเก็บไอเทมปกติ
เสียงเปิดประตูปกติ
โคลนทำการสโลว์ปกติ
รถชนไม่มีการสโลว์หรือสตั๊นใดๆ แก้ได้แก้หรือไม่ก็ได้ไม่น่าเป็นปัญหา
โดนขวดก็เช่นกัน
ตอนส่งงานทำได้ไม่มีปัญหาทำได้หลายทางด้วย
เสียงFปกติ เสียงAปกติ
จบบริบูรณ์ รอเจอกันค่อยดูกันต่อไป
