### ISSUE TITLE
สิ่งที่ต้องแก้ไข

### ISSUE THREAD

**Issue by Donutcmu** [KarnPrasai/ScratchProjectGroup11#21]
- เพิ่มคัทซีน
- ปรับแมพให้ทำง่ายขึ้น
- ปรับปรุงเรื่องการแจงงาน
- ทำโค้ดเพิ่ม

**Comment by Donutcmu** [comment]
- แก้แมพฉากหลัง
- เพิ่มอนิเมชันหมา

**Comment by Donutcmu** [comment]
- ตายแล้วขึ้น f

**Comment by DAVIESBACK** [comment]
- เลขตัวmobไม่ลดทำให้dogมาเรื่อยๆเล่นไม่จบซะที
