### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Donutcmu** [KarnPrasai/ScratchProjectGroup11#9]
ทดสอบเกม

**Comment by Donutcmu** [comment]
- เกมค่อนข้างเล่นยาก (skill issue)
- การดรอปไอเทมกับตัวmobค่อนข้างสมดุล
- ยังมีบัคอยู่
- ยังไม่เพิ่มเสียง
- ถือว่า 85 เปอร์เซนต์

**Comment by DAVIESBACK** [comment]
ควบคุมยาก
ยังมีบัค
ยังไม่มีเสียงเกม
ไอเทมที่ดรอปมาต้องพึ่งดวงเล็กน้อยเพื่อผ่านด่าน
เน้นฝีมือสุดๆ
ต้องการtutorialเพราะตอนเริ่มเกมต้องใช้เวลาหาปุ่มในการตีและขว้างไอแพดเพื่อให้ผู่เล่นเข้าถึงได้

**Comment by Donutcmu** [comment]
- มีการปรับแก้ไขให้เกมมีความพอดี ถือว่าความยากอยู่ในระดับที่ท้าทาย
- ปรับทุกอย่างลงตัว ถือว่าอยู่ที่ 99 percent
- ค่อนข้างสนุก
- อาจจะมีการเพิ่มธีม

**Comment by DAVIESBACK** [comment]
มีการปรับสมดุลให้ตัวเกมเล่นง่ายขึ้นในช่วงแรกและท้าทายมากขึ้นในช่วงหลังทำให้เพิ่มความสนใจได้ดี
อยากให้เพิ่มเสียงมากกว่านี้แต่กลัวโค้ดเดอร์เหนื่อย

**Comment by DAVIESBACK** [comment]
เสียงโอเค 
เกมเพลย์น่าสนใจ 
และข่าวดี บัคไม่มีแล้ว
โดยรวมมีความสมดุล ยาก-ง่าย ดึงดูดคนเล่นได้ดี รวมถึงเสียงที่เพิ่มเข้ามาเพิ่มความน่าสนใจไม่น้อย
สนุกครับ *_*
